# utils/names.py

# List of over 700+ Mexican first names (special characters removed)
first_names = [
    "Alvaro", "Andres", "Antonio", "Carlos", "Daniel", "David", "Diego", "Edgar", "Emilio",
    "Enrique", "Fernando", "Francisco", "Gabriel", "Gustavo", "Hector", "Ignacio", "Javier",
    "Jesus", "Jose", "Juan", "Luis", "Manuel", "Marco", "Miguel", "Omar", "Pedro", "Raul",
    "Ricardo", "Roberto", "Sergio", "Tomas", "Vicente", "Alejandro", "Alberto", "Alfredo",
    "Arturo", "Benjamin", "Bernardo", "Cesar", "Claudio", "Cristobal", "Damian", "Dario",
    "Diego", "Eduardo", "Elias", "Emiliano", "Ernesto", "Esteban", "Felipe", "Fabian",
    "Federico", "Fernando", "Francisco", "Gerardo", "Guillermo", "Hugo", "Ivan", "Israel",
    "Jaime", "Joaquin", "Jonathan", "Jorge", "Josue", "Julio", "Kevin", "Leonel", "Lucas",
    "Luis", "Marcos", "Mario", "Martin", "Mateo", "Mauricio", "Maximiliano", "Miguel Angel",
    "Nicolas", "Oscar", "Pablo", "Patricio", "Paulino", "Pedro", "Ramon", "Renato", "Rodrigo",
    "Ruben", "Salvador", "Samuel", "Santiago", "Sebastian", "Silvio", "Tadeo", "Valentin",
    "Victor", "Xavier", "Yair", "Zacarias", "Adrian", "Agustin", "Aldo", "Alex", "Alfredo",
    "Alonso", "Amado", "Ambrosio", "Americo", "Anacleto", "Anastasio", "Andres", "Angel", "Anselmo",
    "Antonio", "Aquiles", "Arcadio", "Argenis", "Armando", "Arnaldo", "Arsenio", "Arturo", "Asuncion",
    "Atanasio", "Augusto", "Axel", "Balbino", "Baldomero", "Baltasar", "Bartolome", "Basilio", "Benigno",
    "Benjamin", "Bernabe", "Bernardo", "Blas", "Bonifacio", "Brayan", "Buenaventura", "Cain", "Calixto",
    "Camilo", "Canuto", "Capistrano", "Carlo", "Carlos", "Carmelo", "Casimiro", "Cayetano", "Ceferino",
    "Celestino", "Celso", "Cenobio", "Cesareo", "Chano", "Charbel", "Christian", "Christopher", "Claro",
    "Clemente", "Conrado", "Constantino", "Cosme", "Crescencio", "Crisanto", "Cristian", "Cristobal",
    "Cruz", "Damian", "Danilo", "Dario", "David", "Demetrio", "Desiderio", "Diomedes", "Dionisio", "Domingo",
    "Donato", "Dorian", "Duarte", "Eber", "Edgardo", "Eduardo", "Efrain", "Eleuterio", "Elias", "Eliseo",
    "Elpidio", "Eloy", "Emeterio", "Emiliano", "Encarnacion", "Endimion", "Enrique", "Epifanio", "Erasto",
    "Ermilo", "Esau", "Esdras", "Ezequiel", "Fabricio", "Fabio", "Facundo", "Fausto", "Feliciano", "Felipe",
    "Fermin", "Fidencio", "Flavio", "Florentino", "Fortunato", "Franco", "Francisco", "Fredy", "Fulgencio",
    "Gabino", "Gaspar", "Genaro", "Geovanni", "Gerardo", "Gilberto", "Glorioso", "Gonzalo", "Graciano",
    "Gregorio", "Guadalupe", "Gualterio", "Gumersindo", "Gustavo", "Habacuc", "Hector", "Heladio", "Heleodoro",
    "Heriberto", "Hermes", "Hermogenes", "Hernan", "Higinio", "Hipolito", "Homero", "Honorio", "Horacio",
    "Huber", "Humberto", "Hercules", "Iker", "Ildefonso", "Indalecio", "Inocencio", "Irving", "Isaias",
    "Isidoro", "Itamar", "Jacinto", "Jacobo", "Jafet", "Jairo", "Januario", "Jarbas", "Jeremias", "Jeronimo",
    "Joachim", "Joao", "Job", "Jonas", "Jordan", "Jordan", "Jorge", "Josafat", "Jose", "Josue", "Judah", "Julio",
    "Justo", "Kael", "Karim", "Kenji", "Kim", "Kirby", "Kristopher", "Krystian", "Lamberto", "Leandro",
    "Leopoldo", "Librado", "Licurgo", "Lino", "Lisandro", "Lorenzo", "Lucas", "Luciano", "Lucho", "Ludovico",
    "Luis", "Luzbel", "Macario", "Magno", "Maikol", "Malcolm", "Manolo", "Marcelino", "Marcelo", "Marcial",
    "Marciano", "Marcos", "Mariano", "Marino", "Markus", "Martin", "Matheo", "Matias", "Mauricio", "Maximiano",
    "Melchor", "Mercurio", "Miguel", "Moises", "Monte", "Moreno", "Moshe", "Murillo", "Nabor", "Natanael",
    "Nazario", "Neftali", "Nemesio", "Nestor", "Nicodemo", "Nicolas", "Norberto", "Octavio", "Olegario", "Onofre",
    "Orlando", "Ortega", "Osvaldo", "Otelo", "Otilio", "Pabellon", "Pablo", "Panfilo", "Parfait", "Pastor",
    "Patricio", "Paulino", "Pedro", "Pelagio", "Perpetuo", "Petronilo", "Placido", "Polibio", "Primitivo",
    "Quirino", "Raimundo", "Ramiro", "Ramon", "Rebeca", "Reginaldo", "Remigio", "Renato", "Reynaldo", "Ricardo",
    "Rigoberto", "Roque", "Rosendo", "Ruben", "Sabino", "Salomon", "Salvador", "Samuel", "Sancho", "Sandino",
    "Santos", "Saul", "Sebastian", "Segismundo", "Severo", "Silvano", "Silverio", "Simon", "Sixto", "Telesforo",
    "Teodoro", "Teofilo", "Timoteo", "Tito", "Toribio", "Trinidad", "Ulises", "Urbano", "Uriel", "Valentin",
    "Valeriano", "Valerio", "Venancio", "Victoriano", "Vidal", "Vinicio", "Virgilio", "Vladimir", "Wenceslao",
    "Wilmer", "Xavier", "Yago", "Yonatan", "Yosef", "Yuri", "Zacarias", "Zeno", "Zenon", "Zoilo", "Abraham",
    "Adan", "Adolfo", "Agapito", "Agustin", "Alain", "Alan", "Albert", "Aldo", "Alejandro", "Alex", "Alfredo",
    "Alonso", "Amado", "Ambrosio", "Americo", "Anacleto", "Anastasio", "Andres", "Angel", "Anselmo", "Antonio",
    "Aquiles", "Arcadio", "Argenis", "Armando", "Arnaldo", "Arsenio", "Arturo", "Asuncion", "Atanasio", "Augusto",
    "Axel", "Balbino", "Baldomero", "Baltazar", "Bartolome", "Basilio", "Benigno", "Benjamin", "Bernabe", "Bernardo",
    "Blas", "Bonifacio", "Brayan", "Buenaventura", "Cain", "Calixto", "Camilo", "Canuto", "Capistrano", "Carlo",
    "Carlos", "Carmelo", "Casimiro", "Cayetano", "Ceferino", "Celestino", "Celso", "Cenobio", "Cesareo", "Chano",
    "Charbel", "Christian", "Christopher", "Claro", "Clemente", "Conrado", "Constantino", "Cosme", "Crescencio",
    "Crisanto", "Cristian", "Cristobal", "Cruz", "Damian", "Danilo", "Dario", "David", "Demetrio", "Desiderio",
    "Diomedes", "Dionisio", "Domingo", "Donato", "Dorian", "Duarte", "Eber", "Edgardo", "Eduardo", "Efrain",
    "Eleuterio", "Elias", "Eliseo", "Elpidio", "Eloy", "Emeterio", "Emiliano", "Encarnacion", "Endimion", "Enrique",
    "Epifanio", "Erasto", "Ermilo", "Esau", "Esdras", "Ezequiel", "Fabricio", "Fabio", "Facundo", "Fausto",
    "Feliciano", "Felipe", "Fermin", "Fidencio", "Flavio", "Florentino", "Fortunato", "Franco", "Francisco", "Fredy",
    "Fulgencio", "Gabino", "Gaspar", "Genaro", "Geovanni", "Gerardo", "Gilberto", "Glorioso", "Gonzalo", "Graciano",
    "Gregorio", "Guadalupe", "Gualterio", "Gumersindo", "Gustavo", "Habacuc", "Hector", "Heladio", "Heleodoro",
    "Heriberto", "Hermes", "Hermogenes", "Hernan", "Higinio", "Hipolito", "Homero", "Honorio", "Horacio", "Huber",
    "Humberto", "Hercules", "Iker", "Ildefonso", "Indalecio", "Inocencio", "Irving", "Isaias", "Isidoro", "Itamar",
    "Jacinto", "Jacobo", "Jafet", "Jairo", "Januario", "Jarbas", "Jeremias", "Jeronimo", "Joachim", "Joao", "Job",
    "Jonas", "Jordan", "Jordan", "Jorge", "Josafat", "Jose", "Josue", "Judah", "Julio", "Justo", "Kael", "Karim",
    "Kenji", "Kim", "Kirby", "Kristopher", "Krystian", "Lamberto", "Leandro", "Leopoldo", "Librado", "Licurgo",
    "Lino", "Lisandro", "Lorenzo", "Lucas", "Luciano", "Lucho", "Ludovico", "Luis", "Luzbel", "Macario", "Magno",
    "Maikol", "Malcolm", "Manolo", "Marcelino", "Marcelo", "Marcial", "Marciano", "Marcos", "Mariano", "Marino",
    "Markus", "Martin", "Matheo", "Matias", "Mauricio", "Maximiano", "Melchor", "Mercurio", "Miguel", "Moises",
    "Monte", "Moreno", "Moshe", "Murillo", "Nabor", "Natanael", "Nazario", "Neftali", "Nemesio", "Nestor", "Nicodemo",
    "Nicolas", "Norberto", "Octavio", "Olegario", "Onofre", "Orlando", "Ortega", "Osvaldo", "Otelo", "Otilio", "Pabellon",
    "Pablo", "Panfilo", "Parfait", "Pastor", "Patricio", "Paulino", "Pedro", "Pelagio", "Perpetuo", "Petronilo", "Placido",
    "Polibio", "Primitivo", "Quirino", "Raimundo", "Ramiro", "Ramon", "Rebeca", "Reginaldo", "Remigio", "Renato", "Reynaldo",
    "Ricardo", "Rigoberto", "Roque", "Rosendo", "Ruben", "Sabino", "Salomon", "Salvador", "Samuel", "Sancho", "Sandino",
    "Santos", "Saul", "Sebastian", "Segismundo", "Severo", "Silvano", "Silverio", "Simon", "Sixto", "Telesforo", "Teodoro",
    "Teofilo", "Timoteo", "Tito", "Toribio", "Trinidad", "Ulises", "Urbano", "Uriel", "Valentin", "Valeriano", "Valerio",
    "Venancio", "Victoriano", "Vidal", "Vinicio", "Virgilio", "Vladimir", "Wenceslao", "Wilmer", "Xavier", "Yago", "Yonatan",
    "Yosef", "Yuri", "Zacarias", "Zeno", "Zenon", "Zoilo"
]

# List of over 250+ Mexican last names (special characters removed)
last_names = [
    "Alvarez", "Arias", "Bernal", "Castro", "Delgado", "Espinoza", "Fernandez", "Garcia",
    "Gonzalez", "Gutierrez", "Hernandez", "Jimenez", "Lopez", "Martinez", "Medina", "Mendoza",
    "Morales", "Munoz", "Navarro", "Ortega", "Perez", "Ramirez", "Rivera", "Rodriguez",
    "Romero", "Ruiz", "Sanchez", "Soto", "Torres", "Vargas", "Vazquez", "Vega", "Villa",
    "Zamora", "Acosta", "Aguilar", "Aguirre", "Alarcon", "Alvarado", "Andrade", "Ayala",
    "Baez", "Barajas", "Barrios", "Beltran", "Benitez", "Betancourt", "Bustos", "Caballero",
    "Cabrera", "Calderon", "Camacho", "Campbell", "Cardenas", "Carmona", "Castillo",
    "Cervantes", "Contreras", "Cordoba", "Corona", "Cortez", "Cruz", "De Leon", "Dominguez",
    "Duran", "Escobar", "Esquivel", "Fajardo", "Flores", "Gallegos", "Galvan", "Garza",
    "Godoy", "Gomez", "Granados", "Guerrero", "Guzman", "Herrera", "Holguin", "Huerta",
    "Ibarra", "Iglesias", "Islas", "Juarez", "Jurado", "Lara", "Leal", "Ledesma", "Limon",
    "Lozano", "Luna", "Madrid", "Maldonado", "Mancilla", "Manuel", "Marin", "Martin",
    "Mejia", "Menendez", "Miranda", "Montero", "Montoya", "Mora", "Moreno", "Mota",
    "Muniz", "Najera", "Nava", "Nieves", "Noriega", "Nunez", "Obregon", "Olivera",
    "Olivares", "Ortiz", "Padilla", "Palacios", "Palma", "Parra", "Pena", "Peralta",
    "Perez", "Pineda", "Portillo", "Prieto", "Quiroz", "Quinones", "Ramos", "Rangel",
    "Reyes", "Rincon", "Robles", "Rojas", "Romero", "Rosa", "Ruiz", "Salazar", "Saldivar",
    "Salinas", "Sandoval", "Santana", "Santiago", "Saucedo", "Sepulveda", "Silva",
    "Solis", "Suarez", "Tapia", "Terrazas", "Tijerina", "Trejo", "Trujillo", "Ugalde",
    "Valdez", "Valencia", "Valenzuela", "Velarde", "Velasco", "Vela", "Villarreal",
    "Villatoro", "Villavecencio", "Villasenor", "Villaverde", "Villena", "Villoria",
    "Vincente", "Vinueza", "Yanez", "Zambrano", "Zepeda", "Zuniga", "Acevedo", "Acuna",
    "Adame", "Aguayo", "Ahumada", "Alba", "Alcala", "Alcaraz", "Alfaro", "Aliaga",
    "Allende", "Almanza", "Altamirano", "Alvaro", "Amaya", "Ambriz", "Amaya", "Amores",
    "Ancira", "Andino", "Angulo", "Apodaca", "Aragon", "Arce", "Arellano", "Arguello",
    "Armenta", "Arredondo", "Arrona", "Arroyo", "Arteaga", "Ascencio", "Astorga", "Avila",
    "Ayala", "Azcona", "Azpeitia", "Badillo", "Banos", "Barrientos", "Barron", "Batista",
    "Bejarano", "Beltran", "Benavides", "Beristain", "Berumen", "Bolanos", "Bonilla",
    "Botello", "Bracamontes", "Bravo", "Breceda", "Brito", "Buendia", "Burciaga", "Bustos",
    "Caballero", "Cabrera", "Cadena", "Cadavid", "Cadenas", "Caffarel", "Calderon",
    "Calvo", "Camacho", "Camarena", "Campos", "Canales", "Cano", "Cantu", "Carbonell",
    "Cardenas", "Cardona", "Carmona", "Carrasco", "Carrera", "Carreon", "Castaneda",
    "Castellanos", "Castillo", "Castorena", "Catalan", "Cavazos", "Cerda", "Cervantes",
    "Chapa", "Chavez"
]